### ISSUE TITLE
Installation on an already running nginx vps ?

### ISSUE THREAD

**Issue by rubensben** [jprjr/multistreamer-installer#11]
Hi @jprjr and thank you for the great work ! I have some issues managing to run the docker image on my vps as I followed you great video here : https://youtu.be/HdDDtBOLme4?t=1228

On my vps/host, an nginx instance is already running and manage all of our websites, so I decided to move the 8081 port to 8085. Same for rmtp, there is already one running for our live streams so I moved the port 1935 to 1937. I have opened the following ports on my firewall (dunno if I have too by the way) :  8085,6667,1937
VPS :  Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-45-generic x86_64)

So basically I can't access to the website (error 500) as I believe everything is well configured. Here is my configuration : 

docker-compose.override.yml
```
redisio:
  volumes:
   - /home/admin/conf/web:/etc/ssl
   - /srv/docker/multistreamer/redis:/var/lib/redis:Z
postgresql:
  volumes:
   - /home/admin/conf/web:/etc/ssl
   - /srv/docker/multistreamer/postgresql:/var/lib/postgresql:Z
  environment:
   - POSTGRES_USER=multistreamer
   - POSTGRES_PASS=password
multistreamer:
  ports:
   - "185.19.29.84:8085:8081"
   - "6667:6667"
   - "1937:1935"
  volumes:
   - /home/admin/conf/web:/etc/ssl
   - /srv/docker/multistreamer/multistreamer:/etc/multistreamer:Z
   - ./htpasswd:/etc/htpasswd-auth-server:Z
  environment:
   MULTISTREAMER_APP_NAME: multistreamer
   MULTISTREAMER_LANG_ID: en_us
   MULTISTREAMER_AUTH_ENDPOINT: 
   MULTISTREAMER_SESSION_SECRET: 123456
   MULTISTREAMER_PUBLIC_HTTP_URL: https://onair.solarsoundsystem.org
   MULTISTREAMER_PUBLIC_RTMP_URL: rtmp://onair.solarsoundsystem.org:1937
   MULTISTREAMER_RTMP_PREFIX: multistreamer
   MULTISTREAMER_HTTP_PREFIX: 
   MULTISTREAMER_PUBLIC_IRC_HOSTNAME: onair.solarsoundsystem.org
   MULTISTREAMER_PUBLIC_IRC_PORT: 6667
   MULTISTREAMER_TWITCH_CLIENT_ID: 
   MULTISTREAMER_TWITCH_CLIENT_SECRET: 
   MULTISTREAMER_TWITCH_INGEST_SERVER: 
   MULTISTREAMER_YOUTUBE_CLIENT_ID: 
   MULTISTREAMER_YOUTUBE_CLIENT_SECRET: 
   MULTISTREAMER_YOUTUBE_COUNTRY_CODE: 
   MULTISTREAMER_FACEBOOK_APP_ID: 
   MULTISTREAMER_FACEBOOK_APP_SECRET: 
   MULTISTREAMER_MIXER_CLIENT_ID: 
   MULTISTREAMER_MIXER_CLIENT_SECRET: 
   MULTISTREAMER_MIXER_INGEST_SERVER: 
   MULTISTREAMER_LOG_LEVEL: error
   MULTISTREAMER_PUBLIC_IRC_SSL: 'false'
   MULTISTREAMER_SESSION_NAME: multistreamer
   MULTISTREAMER_LOQ_QUERIES: 'false'
   MULTISTREAMER_LOQ_REQUESTS: 'false'
   MULTISTREAMER_IRC_FORCE_JOIN: 'false'
   MULTISTREAMER_WORKER_PROCESSES: 1
   MULTISTREAMER_DNS_RESOLVER: 127.0.0.1:5353 ipv6=off
   MULTISTREAMER_DICT_STREAMS_SIZE: 10m
   MULTISTREAMER_DICT_WRITERS_SIZE: 10m
   MULTISTREAMER_FFMPEG_MAX_ATTEMPTS: 3
   MULTISTREAMER_PING: 1m
   MULTISTREAMER_PING_TIMEOUT: 30s
   MULTISTREAMER_SHOW_VERSION: 'true'
   MULTISTREAMER_IRC_MOTD: |-
     Welcome to the SolarSoundSystem IRC server!
     Shine On.
```

On the host, here is my nginx configuration :  
```
server {
    listen      185.19.29.84:443 http2;
    server_name onair.solarsoundsystem.org ;
    ssl         on;
    ssl_certificate      /home/admin/conf/web/ssl.onair.solarsoundsystem.org.pem;
    ssl_certificate_key  /home/admin/conf/web/ssl.onair.solarsoundsystem.org.key;
    error_log  /var/log/httpd/domains/onair.solarsoundsystem.org.error.log error;
 
      location / {
	proxy_pass https://185.19.29.84:8085;
	proxy_request_buffering off;
	proxy_http_version 1.1;
	#proxy_redirect http:// https://;
}

      location /ws {
	proxy_pass https://185.19.29.84:8085;
	proxy_request_buffering off;
	proxy_http_version 1.1;
	#proxy_redirect http:// https://;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";

    }

    location /error/ {
        alias   /home/admin/web/onair.solarsoundsystem.org/document_errors/;
    }

    location @fallback {
        proxy_pass      https://185.19.29.84:8443;
    }

    include /home/admin/conf/web/snginx.onair.solarsoundsystem.org.conf*;
}

```

docker-compose up
```
Starting docker-multistreamer_postgresql_1 ... done
Starting docker-multistreamer_redisio_1    ... done
Recreating docker-multistreamer_multistreamer_1 ... done
Attaching to docker-multistreamer_postgresql_1, docker-multistreamer_redisio_1, docker-multistreamer_multistreamer_1
postgresql_1     | 2019-03-05 13:49:56.221 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgresql_1     | 2019-03-05 13:49:56.221 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgresql_1     | 2019-03-05 13:49:56.226 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresql_1     | 2019-03-05 13:49:56.249 UTC [23] LOG:  database system was shut down at 2019-03-05 13:49:39 UTC
postgresql_1     | 2019-03-05 13:49:56.261 UTC [1] LOG:  database system is ready to accept connections
redisio_1        | 1:C 05 Mar 2019 13:49:56.265 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redisio_1        | 1:C 05 Mar 2019 13:49:56.265 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=1, just started
redisio_1        | 1:C 05 Mar 2019 13:49:56.265 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redisio_1        | 1:M 05 Mar 2019 13:49:56.267 * Running mode=standalone, port=6379.
redisio_1        | 1:M 05 Mar 2019 13:49:56.267 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redisio_1        | 1:M 05 Mar 2019 13:49:56.267 # Server initialized
redisio_1        | 1:M 05 Mar 2019 13:49:56.267 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redisio_1        | 1:M 05 Mar 2019 13:49:56.267 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redisio_1        | 1:M 05 Mar 2019 13:49:56.267 * DB loaded from disk: 0.000 seconds
redisio_1        | 1:M 05 Mar 2019 13:49:56.268 * Ready to accept connections
multistreamer_1  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
multistreamer_1  | [s6-init] ensuring user provided files have correct perms...exited 0.
multistreamer_1  | [fix-attrs.d] applying ownership & permissions fixes...
multistreamer_1  | [fix-attrs.d] done.
multistreamer_1  | [cont-init.d] executing container initialization scripts...
multistreamer_1  | [cont-init.d] 01-setup: executing...
multistreamer_1  | [cont-init.d] 01-setup: exited 0.
multistreamer_1  | [cont-init.d] done.
multistreamer_1  | [services.d] starting services
multistreamer_1  | [services.d] done.
```
And what I have when accessing to https://onair.solarsoundsystem.org/ is only a 500 error message, without any error logs in nginx or apache

Any idea ? Thanks in advance for your help ! Really looking forward making it work
